### ISSUE TITLE
Refined support

### ISSUE THREAD

**Issue by tabdulradi** [tpolecat/atto#78]
I wrote [this](https://github.com/tabdulradi/opentracing-xray/blob/master/src/main/scala/com/abdulradi/opentracing/xray/v1/jaeger/ConvertionOps.scala#L140-L152). Would like it to be part of the library? maybe a separate module?

**Comment by tpolecat** [comment]
Sure, sorry for the delay, my alerts were messed up. I'll take a PR, or just inline the snippet here and I'll set it up. You're correct that it will require another module.
